baseURL = "https://fikzhry.netlify.app/"
title = "semesta"

languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "cerita tentang keanehan alam semesta"  
  dark = "on"
  highlight = true
  lottie = "private_files/lf30_4bkst7vs"

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
